# Generated by Django 5.0.2 on 2024-03-01 12:50

from django.db import migrations, models



class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthenticatedMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=100)),
                ("hash_value", models.CharField(max_length=64)),
            ],
        ),
    ]
